# Generated by Django 4.2 on 2023-12-20 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movieinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nation_korean', models.BooleanField(default=False)),
                ('nation_foreign', models.BooleanField(default=False)),
                ('period_2000', models.BooleanField(default=False)),
                ('period_2010', models.BooleanField(default=False)),
                ('period_2020', models.BooleanField(default=False)),
                ('movie_title', models.TextField()),
                ('poster_url', models.URLField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('genre', models.ManyToManyField(related_name='recommends', to='movieinfo.genre')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommends', to='movieinfo.movieinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
