# Generated by Django 4.2 on 2023-12-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('password', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=255)),
                ('profile_picture', models.CharField(max_length=100)),
                ('introduction', models.TextField()),
            ],
        ),
    ]
