# Generated by Django 4.2 on 2023-12-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieinfo', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tag',
        ),
        migrations.AddField(
            model_name='user',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, to='movieinfo.genre'),
        ),
    ]
