# Generated by Django 4.2 on 2023-12-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieinfo', '0001_initial'),
        ('accounts', '0002_remove_user_tag_user_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='genre',
        ),
        migrations.AddField(
            model_name='user',
            name='ganre',
            field=models.ManyToManyField(blank=True, to='movieinfo.genre'),
        ),
    ]
