# Generated by Django 4.2 on 2023-12-12 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('searchTitle', models.TextField()),
                ('title', models.TextField()),
                ('posters', models.TextField(blank=True, null=True)),
                ('vods', models.TextField(blank=True, null=True)),
                ('directors', models.CharField(blank=True, max_length=64, null=True)),
                ('actors', models.TextField(blank=True, null=True)),
                ('nations', models.CharField(blank=True, max_length=64, null=True)),
                ('companies', models.TextField(blank=True, null=True)),
                ('plot', models.TextField(blank=True, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('rating', models.CharField(blank=True, max_length=64, null=True)),
                ('genres', models.CharField(blank=True, max_length=64, null=True)),
                ('releaseDate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OneLineCritic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('starpoint', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieinfo.movieinfo')),
            ],
        ),
    ]
