# Generated by Django 4.2 on 2023-12-14 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestWatchlistMovie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieinfo.movieinfo')),
            ],
        ),
        migrations.CreateModel(
            name='TestWatchedMovie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieinfo.movieinfo')),
            ],
        ),
        migrations.CreateModel(
            name='TestLikeMovie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieinfo.movieinfo')),
            ],
        ),
    ]
