# Generated by Django 4.2 on 2023-12-23 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieinfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testwatchedmovie',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='testwatchlistmovie',
            name='movie',
        ),
        migrations.DeleteModel(
            name='TestLikeMovie',
        ),
        migrations.DeleteModel(
            name='TestWatchedMovie',
        ),
        migrations.DeleteModel(
            name='TestWatchlistMovie',
        ),
    ]
