# Generated by Django 4.2 on 2023-12-28 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieinfo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GPTAnalysis',
        ),
    ]
