# Generated by Django 4.2 on 2023-12-17 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieinfo', '0002_testwatchlistmovie_testwatchedmovie_testlikemovie'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPTAnalysis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('num_of_critics', models.IntegerField(blank=True, null=True)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movieinfo.movieinfo')),
            ],
        ),
    ]
